Vagrant.configure('2') do |config |
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = ENV['OS_KEY_PAIR_FILE']
  config.vm.provider :openstack do |os, override |
    os.identity_api_version = '3'
    os.openstack_auth_url   = ENV['OS_AUTH_URL']
    os.domain_name          = ENV['OS_USER_DOMAIN_NAME']
    os.username             = ENV['OS_USERNAME']
    os.password             = ENV['OS_PASSWORD']
    os.project_name         = ENV['OS_PROJECT_NAME']
    os.keypair_name         = ENV['OS_KEY_PAIR_NAME']
    os.image                = ENV['OS_IMAGE']
    os.flavor               = ENV['OS_FLAVOR']
    override.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.define 'server-1' do |s|
    s.vm.provider :openstack do |os|
      os.server_name        = 'AT12SALO01'
    end
  end
  config.vm.provision "docker"
  config.vm.provision "docker_compose"
  config.vm.provision "file", source: "docker_compose.yml", destination: "/home/ubuntu/docker_compose.yml"
  config.vm.provision "shell", inline: "docker-compose -f docker_compose.yml up -d"
end