Vagrant.configure('2') do |config |
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = ENV['OS_KEY_PAIR_FILE']
  config.vm.provider :openstack do |os, override |
    os.identity_api_version = '3'
    os.openstack_auth_url   = ENV['OS_AUTH_URL']
    os.domain_name          = ENV['OS_USER_DOMAIN_NAME']
    os.username             = ENV['OS_USERNAME']
    os.password             = ENV['OS_PASSWORD']
    os.project_name         = ENV['OS_PROJECT_NAME']
    os.keypair_name         = ENV['OS_KEY_PAIR_NAME']
    os.image                = ENV['OS_IMAGE']
    os.flavor               = ENV['OS_FLAVOR']
    override.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.provision "docker"
  config.vm.provision "docker_compose"

  config.vm.define 'server-1' do |s|
    s.vm.provider :openstack do |os|
      os.server_name        = 'AT12SALO01'
    end
  end

  config.vm.define 'sonarqube' do |s|
    s.vm.provider :openstack do |os|
      os.server_name        = 'AT12SALO02'
    end
    s.vm.provision "file", source: "sonarqube/database.env", destination: "/home/ubuntu/database.env"
    s.vm.provision "file", source: "sonarqube/sonar.env", destination: "/home/ubuntu/sonar.env"
    s.vm.provision "file", source: "sonarqube/docker-compose.yml", destination: "/home/ubuntu/docker-compose.yml"
    s.vm.provision "shell", inline: "docker-compose up -d"
    s.vm.provision "shell", inline: "rm /home/ubuntu/*.env"
    s.vm.provision "shell", inline: "rm /home/ubuntu/*.yml"
  end
end
