Vagrant.configure('2') do |config |
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = ENV['OS_KEY_PAIR_FILE']
  config.vm.provider :openstack do |os, override |
    os.identity_api_version = '3'
    os.openstack_auth_url   = ENV['OS_AUTH_URL']
    os.domain_name          = ENV['OS_USER_DOMAIN_NAME']
    os.username             = ENV['OS_USERNAME']
    os.password             = ENV['OS_PASSWORD']
    os.project_name         = ENV['OS_PROJECT_NAME']
    os.keypair_name         = ENV['OS_KEY_PAIR_NAME']
    os.image                = ENV['OS_IMAGE']
    os.flavor               = ENV['OS_FLAVOR']
    override.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.provision "docker"
  config.vm.provision "docker_compose"
  # jenkins
  config.vm.define 'server-1' do |s|
    s.vm.provider :openstack do |os|
      os.server_name        = 'AT12SALO01'
    end
    s.vm.provision :docker do |docker|
      docker.run "jenkins",
      image: "registry.jala.info/devops/jenkins/jenkins:2.255-alpine",
      args: "-p 80:8080 " +
        "-v jenkins_home:/var/jenkins_home"
    end
  end
  # jenkinsBlueocean
  config.vm.define 'server-2' do |s|
    s.vm.provider :openstack do |os|
      os.server_name        = 'AT12SALO02'
    end
    s.vm.provision "file", source: "docker-compose/blueocean/docker-compose.yml", destination: "/home/ubuntu/docker-compose.yml"
    s.vm.provision "shell", inline: "docker-compose -f docker-compose.yml up -d"
    s.vm.provision "shell", inline: "rm /home/ubuntu/*.yml"
  end
  #SQL Server
  config.vm.define 'server-3' do |s|
    s.vm.provider :openstack do |os|
      os.server_name        = 'AT12SALO03'
    end
    s.vm.provision "file", source: "docker-compose/mssql/.env", destination: "/home/ubuntu/.env"
    s.vm.provision "file", source: "docker-compose/mssql/docker-compose.yml", destination: "/home/ubuntu/docker-compose.yml"
    s.vm.provision "shell", inline: "docker-compose up -d"
    s.vm.provision "shell", inline: "rm /home/ubuntu/.env"
    s.vm.provision "shell", inline: "rm /home/ubuntu/docker_compose.yml"
  end
  # Sonarqube
  config.vm.define 'server-4' do |s|
    s.vm.provider :openstack do |os|
      os.server_name        = 'AT12SALO04'
    end
    s.vm.provision "file", source: "docker-compose/sonarqube/database.env", destination: "/home/ubuntu/database.env"
    s.vm.provision "file", source: "docker-compose/sonarqube/sonar.env", destination: "/home/ubuntu/sonar.env"
    s.vm.provision "file", source: "docker-compose/sonarqube/docker-compose.yml", destination: "/home/ubuntu/docker-compose.yml"
    s.vm.provision "shell", inline: "docker-compose up -d"
    s.vm.provision "shell", inline: "rm /home/ubuntu/*.env"
    s.vm.provision "shell", inline: "rm /home/ubuntu/docker-compose.yml"
  end
  # gocd
  config.vm.define 'server-5' do |s|
    s.vm.provider :openstack do |os|
      os.server_name        = 'AT12SALO05'
    end
    s.vm.provision "file", source: "docker-compose/gocd/docker-compose.yml", destination: "/home/ubuntu/docker-compose.yml"
    s.vm.provision "shell", inline: "docker-compose up -d"
  end
end
