Vagrant.configure('2') do |config |
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = "/home/sam/fjala/devops/sl-devops-key.pem"
  config.vm.provider :openstack do |os, override |
    os.identity_api_version = '3'
    os.openstack_auth_url = 'http://10.28.3.240:5000/v3'
    os.domain_name = 'fundacion-jala'
    os.username = 'SamuelLoza'
    os.password = ENV['OS_PASSWORD']
    os.project_name = 'fj_at12'
    os.keypair_name = 'sl-devops-key'
    os.image = 'ubuntu-18.04-server_20200326'
    os.flavor = 'student.2.4R'
    os.server_name = 'AT12SALO01'
    override.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  SHELL
end
