Vagrant.configure("2") do |config|
 config.vm.box       = "ubuntu/bionic64"
 config.vm.define 'server-1' do |s|
  s.vm.provider :virtualbox do |v|
    v.name = 'AT12SAL01'
    v.memory = 2048
    v.cpus = 2
  end
  s.vm.provision "docker"
  s.vm.provision "shell", path: "scripts/install_jenkins.sh"
 end
end
